version: '2'
services:
    equinooxe-app:
        image: equinooxe
        external_links:
            - equinooxe-mysql:mysql
            - equinooxe-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/equinooxe?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    equinooxe-mysql:
        extends:
            file: mysql.yml
            service: equinooxe-mysql
    equinooxe-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: equinooxe-elasticsearch
